// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ai.dart';
import 'api/analyze.dart';
import 'api/four.dart';
import 'api/game.dart';
import 'api/net.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ChessGamePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGamePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FourGamePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGamePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ChessGame
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    dynamic raw,
  );

  @protected
  FourGame
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    dynamic raw,
  );

  @protected
  ChessGame
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    dynamic raw,
  );

  @protected
  FourGame
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    dynamic raw,
  );

  @protected
  ChessGame
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    dynamic raw,
  );

  @protected
  FourGame
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    dynamic raw,
  );

  @protected
  ChessGame
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    dynamic raw,
  );

  @protected
  FourGame
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    dynamic raw,
  );

  @protected
  RustStreamSink<AiUpdate> dco_decode_StreamSink_ai_update_Sse(dynamic raw);

  @protected
  RustStreamSink<AnalysisUpdate> dco_decode_StreamSink_analysis_update_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<NetEvent> dco_decode_StreamSink_net_event_Sse(dynamic raw);

  @protected
  RustStreamSink<NetHost> dco_decode_StreamSink_net_host_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiConfigDto dco_decode_ai_config_dto(dynamic raw);

  @protected
  AiUpdate dco_decode_ai_update(dynamic raw);

  @protected
  AnalysisUpdate dco_decode_analysis_update(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiConfigDto dco_decode_box_autoadd_ai_config_dto(dynamic raw);

  @protected
  FourPieceKind dco_decode_box_autoadd_four_piece_kind(dynamic raw);

  @protected
  FourSquarePiece dco_decode_box_autoadd_four_square_piece(dynamic raw);

  @protected
  PieceKind dco_decode_box_autoadd_piece_kind(dynamic raw);

  @protected
  SquarePiece dco_decode_box_autoadd_square_piece(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ClockSnapshot dco_decode_clock_snapshot(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FourFormat dco_decode_four_format(dynamic raw);

  @protected
  FourPieceKind dco_decode_four_piece_kind(dynamic raw);

  @protected
  FourPlayer dco_decode_four_player(dynamic raw);

  @protected
  FourPlayerPanel dco_decode_four_player_panel(dynamic raw);

  @protected
  FourPlayerStatus dco_decode_four_player_status(dynamic raw);

  @protected
  FourSquarePiece dco_decode_four_square_piece(dynamic raw);

  @protected
  FourView dco_decode_four_view(dynamic raw);

  @protected
  GameOutcome dco_decode_game_outcome(dynamic raw);

  @protected
  GameVariant dco_decode_game_variant(dynamic raw);

  @protected
  GameView dco_decode_game_view(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<bool> dco_decode_list_bool(dynamic raw);

  @protected
  List<FourPlayerPanel> dco_decode_list_four_player_panel(dynamic raw);

  @protected
  List<FourSquarePiece?> dco_decode_list_opt_box_autoadd_four_square_piece(
    dynamic raw,
  );

  @protected
  List<SquarePiece?> dco_decode_list_opt_box_autoadd_square_piece(dynamic raw);

  @protected
  List<PieceKind> dco_decode_list_piece_kind(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MoveOutcome dco_decode_move_outcome(dynamic raw);

  @protected
  NetEvent dco_decode_net_event(dynamic raw);

  @protected
  NetEventKind dco_decode_net_event_kind(dynamic raw);

  @protected
  NetHost dco_decode_net_host(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FourPieceKind? dco_decode_opt_box_autoadd_four_piece_kind(dynamic raw);

  @protected
  FourSquarePiece? dco_decode_opt_box_autoadd_four_square_piece(dynamic raw);

  @protected
  PieceKind? dco_decode_opt_box_autoadd_piece_kind(dynamic raw);

  @protected
  SquarePiece? dco_decode_opt_box_autoadd_square_piece(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PieceColor dco_decode_piece_color(dynamic raw);

  @protected
  PieceKind dco_decode_piece_kind(dynamic raw);

  @protected
  SquarePiece dco_decode_square_piece(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ChessGame
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    SseDeserializer deserializer,
  );

  @protected
  FourGame
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    SseDeserializer deserializer,
  );

  @protected
  ChessGame
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    SseDeserializer deserializer,
  );

  @protected
  FourGame
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    SseDeserializer deserializer,
  );

  @protected
  ChessGame
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    SseDeserializer deserializer,
  );

  @protected
  FourGame
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    SseDeserializer deserializer,
  );

  @protected
  ChessGame
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    SseDeserializer deserializer,
  );

  @protected
  FourGame
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AiUpdate> sse_decode_StreamSink_ai_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AnalysisUpdate> sse_decode_StreamSink_analysis_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NetEvent> sse_decode_StreamSink_net_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NetHost> sse_decode_StreamSink_net_host_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiConfigDto sse_decode_ai_config_dto(SseDeserializer deserializer);

  @protected
  AiUpdate sse_decode_ai_update(SseDeserializer deserializer);

  @protected
  AnalysisUpdate sse_decode_analysis_update(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiConfigDto sse_decode_box_autoadd_ai_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  FourPieceKind sse_decode_box_autoadd_four_piece_kind(
    SseDeserializer deserializer,
  );

  @protected
  FourSquarePiece sse_decode_box_autoadd_four_square_piece(
    SseDeserializer deserializer,
  );

  @protected
  PieceKind sse_decode_box_autoadd_piece_kind(SseDeserializer deserializer);

  @protected
  SquarePiece sse_decode_box_autoadd_square_piece(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ClockSnapshot sse_decode_clock_snapshot(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FourFormat sse_decode_four_format(SseDeserializer deserializer);

  @protected
  FourPieceKind sse_decode_four_piece_kind(SseDeserializer deserializer);

  @protected
  FourPlayer sse_decode_four_player(SseDeserializer deserializer);

  @protected
  FourPlayerPanel sse_decode_four_player_panel(SseDeserializer deserializer);

  @protected
  FourPlayerStatus sse_decode_four_player_status(SseDeserializer deserializer);

  @protected
  FourSquarePiece sse_decode_four_square_piece(SseDeserializer deserializer);

  @protected
  FourView sse_decode_four_view(SseDeserializer deserializer);

  @protected
  GameOutcome sse_decode_game_outcome(SseDeserializer deserializer);

  @protected
  GameVariant sse_decode_game_variant(SseDeserializer deserializer);

  @protected
  GameView sse_decode_game_view(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer);

  @protected
  List<FourPlayerPanel> sse_decode_list_four_player_panel(
    SseDeserializer deserializer,
  );

  @protected
  List<FourSquarePiece?> sse_decode_list_opt_box_autoadd_four_square_piece(
    SseDeserializer deserializer,
  );

  @protected
  List<SquarePiece?> sse_decode_list_opt_box_autoadd_square_piece(
    SseDeserializer deserializer,
  );

  @protected
  List<PieceKind> sse_decode_list_piece_kind(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MoveOutcome sse_decode_move_outcome(SseDeserializer deserializer);

  @protected
  NetEvent sse_decode_net_event(SseDeserializer deserializer);

  @protected
  NetEventKind sse_decode_net_event_kind(SseDeserializer deserializer);

  @protected
  NetHost sse_decode_net_host(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FourPieceKind? sse_decode_opt_box_autoadd_four_piece_kind(
    SseDeserializer deserializer,
  );

  @protected
  FourSquarePiece? sse_decode_opt_box_autoadd_four_square_piece(
    SseDeserializer deserializer,
  );

  @protected
  PieceKind? sse_decode_opt_box_autoadd_piece_kind(
    SseDeserializer deserializer,
  );

  @protected
  SquarePiece? sse_decode_opt_box_autoadd_square_piece(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PieceColor sse_decode_piece_color(SseDeserializer deserializer);

  @protected
  PieceKind sse_decode_piece_kind(SseDeserializer deserializer);

  @protected
  SquarePiece sse_decode_square_piece(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    ChessGame self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    FourGame self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    ChessGame self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    FourGame self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    ChessGame self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    FourGame self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    ChessGame self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    FourGame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ai_update_Sse(
    RustStreamSink<AiUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_analysis_update_Sse(
    RustStreamSink<AnalysisUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_net_event_Sse(
    RustStreamSink<NetEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_net_host_Sse(
    RustStreamSink<NetHost> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_config_dto(AiConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_ai_update(AiUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_analysis_update(
    AnalysisUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_config_dto(
    AiConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_four_piece_kind(
    FourPieceKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_four_square_piece(
    FourSquarePiece self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_piece_kind(
    PieceKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_square_piece(
    SquarePiece self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_clock_snapshot(ClockSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_four_format(FourFormat self, SseSerializer serializer);

  @protected
  void sse_encode_four_piece_kind(FourPieceKind self, SseSerializer serializer);

  @protected
  void sse_encode_four_player(FourPlayer self, SseSerializer serializer);

  @protected
  void sse_encode_four_player_panel(
    FourPlayerPanel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_four_player_status(
    FourPlayerStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_four_square_piece(
    FourSquarePiece self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_four_view(FourView self, SseSerializer serializer);

  @protected
  void sse_encode_game_outcome(GameOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_game_variant(GameVariant self, SseSerializer serializer);

  @protected
  void sse_encode_game_view(GameView self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_list_four_player_panel(
    List<FourPlayerPanel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_opt_box_autoadd_four_square_piece(
    List<FourSquarePiece?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_opt_box_autoadd_square_piece(
    List<SquarePiece?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_piece_kind(
    List<PieceKind> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_move_outcome(MoveOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_net_event(NetEvent self, SseSerializer serializer);

  @protected
  void sse_encode_net_event_kind(NetEventKind self, SseSerializer serializer);

  @protected
  void sse_encode_net_host(NetHost self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_four_piece_kind(
    FourPieceKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_four_square_piece(
    FourSquarePiece? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_piece_kind(
    PieceKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_square_piece(
    SquarePiece? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_piece_color(PieceColor self, SseSerializer serializer);

  @protected
  void sse_encode_piece_kind(PieceKind self, SseSerializer serializer);

  @protected
  void sse_encode_square_piece(SquarePiece self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGamePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_chess_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGamePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGamePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_chess_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGame =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChessGamePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGamePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_chess_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGamePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGamePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_chess_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGame =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFourGamePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
