// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'game.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `reg`, `registry`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RegistryGuard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `drop`, `fmt`, `fmt`

/// Run a search for `fen`, streaming progress. `search_id` identifies it for
/// cancellation. Runs off the UI thread (StreamSink param).
Stream<AiUpdate> aiSearch({
  required BigInt searchId,
  required String fen,
  required AiConfigDto config,
  required Uint64List history,
  required GameVariant variant,
  required int whiteChecks,
  required int blackChecks,
  required List<int> whiteHand,
  required List<int> blackHand,
  required BigInt promoted,
}) => RustLib.instance.api.crateApiAiAiSearch(
  searchId: searchId,
  fen: fen,
  config: config,
  history: history,
  variant: variant,
  whiteChecks: whiteChecks,
  blackChecks: blackChecks,
  whiteHand: whiteHand,
  blackHand: blackHand,
  promoted: promoted,
);

/// Request cancellation of the search with `search_id`.
void aiCancel({required BigInt searchId}) =>
    RustLib.instance.api.crateApiAiAiCancel(searchId: searchId);

/// Difficulty configuration passed from Dart.
class AiConfigDto {
  final int maxDepth;
  final BigInt? moveTimeMs;
  final int evalNoise;
  final double blunderChance;
  final int topNRandom;
  final int contempt;
  final BigInt seed;

  const AiConfigDto({
    required this.maxDepth,
    this.moveTimeMs,
    required this.evalNoise,
    required this.blunderChance,
    required this.topNRandom,
    required this.contempt,
    required this.seed,
  });

  @override
  int get hashCode =>
      maxDepth.hashCode ^
      moveTimeMs.hashCode ^
      evalNoise.hashCode ^
      blunderChance.hashCode ^
      topNRandom.hashCode ^
      contempt.hashCode ^
      seed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiConfigDto &&
          runtimeType == other.runtimeType &&
          maxDepth == other.maxDepth &&
          moveTimeMs == other.moveTimeMs &&
          evalNoise == other.evalNoise &&
          blunderChance == other.blunderChance &&
          topNRandom == other.topNRandom &&
          contempt == other.contempt &&
          seed == other.seed;
}

/// One progress update from the search.
class AiUpdate {
  final int depth;
  final int scoreCp;
  final String bestUci;
  final List<String> pv;
  final BigInt nodes;
  final bool done;

  const AiUpdate({
    required this.depth,
    required this.scoreCp,
    required this.bestUci,
    required this.pv,
    required this.nodes,
    required this.done,
  });

  @override
  int get hashCode =>
      depth.hashCode ^
      scoreCp.hashCode ^
      bestUci.hashCode ^
      pv.hashCode ^
      nodes.hashCode ^
      done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiUpdate &&
          runtimeType == other.runtimeType &&
          depth == other.depth &&
          scoreCp == other.scoreCp &&
          bestUci == other.bestUci &&
          pv == other.pv &&
          nodes == other.nodes &&
          done == other.done;
}
