// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `classify`, `mate_in_from`, `mate_white`, `material`, `piece_val`, `white_cp`, `win_prob`, `win_stm`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Analyze `moves` played from `start_fen`. `depth` is the fixed search depth
/// per position. Streams an [`AnalysisUpdate`] per ply, then a `done` update.
Stream<AnalysisUpdate> analyzeGame({
  required String startFen,
  required List<String> moves,
  required int depth,
}) => RustLib.instance.api.crateApiAnalyzeAnalyzeGame(
  startFen: startFen,
  moves: moves,
  depth: depth,
);

/// Cancel the running analysis.
void analysisCancel() => RustLib.instance.api.crateApiAnalyzeAnalysisCancel();

class AnalysisUpdate {
  final int ply;
  final String uci;
  final String san;

  /// Evaluation after the move, White's point of view, clamped to ±10000.
  final int evalCp;

  /// 0 = not mate; otherwise signed plies-to-mate (White mating > 0).
  final int mateIn;

  /// Evaluation of the position *before* the move (best play), White POV.
  /// Lets the eval bar/graph show a real value at the start ply.
  final int evalBeforeCp;

  /// Signed plies-to-mate for the position before the move (White mating > 0).
  final int mateBeforeIn;
  final String bestUci;

  /// Engine's best move in SAN (for human-readable coach explanations).
  final String bestSan;
  final int cpLoss;
  final String classification;
  final int progress;
  final int total;
  final bool done;
  final double whiteAccuracy;
  final double blackAccuracy;

  const AnalysisUpdate({
    required this.ply,
    required this.uci,
    required this.san,
    required this.evalCp,
    required this.mateIn,
    required this.evalBeforeCp,
    required this.mateBeforeIn,
    required this.bestUci,
    required this.bestSan,
    required this.cpLoss,
    required this.classification,
    required this.progress,
    required this.total,
    required this.done,
    required this.whiteAccuracy,
    required this.blackAccuracy,
  });

  @override
  int get hashCode =>
      ply.hashCode ^
      uci.hashCode ^
      san.hashCode ^
      evalCp.hashCode ^
      mateIn.hashCode ^
      evalBeforeCp.hashCode ^
      mateBeforeIn.hashCode ^
      bestUci.hashCode ^
      bestSan.hashCode ^
      cpLoss.hashCode ^
      classification.hashCode ^
      progress.hashCode ^
      total.hashCode ^
      done.hashCode ^
      whiteAccuracy.hashCode ^
      blackAccuracy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisUpdate &&
          runtimeType == other.runtimeType &&
          ply == other.ply &&
          uci == other.uci &&
          san == other.san &&
          evalCp == other.evalCp &&
          mateIn == other.mateIn &&
          evalBeforeCp == other.evalBeforeCp &&
          mateBeforeIn == other.mateBeforeIn &&
          bestUci == other.bestUci &&
          bestSan == other.bestSan &&
          cpLoss == other.cpLoss &&
          classification == other.classification &&
          progress == other.progress &&
          total == other.total &&
          done == other.done &&
          whiteAccuracy == other.whiteAccuracy &&
          blackAccuracy == other.blackAccuracy;
}
