// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'game.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_format`, `from_kind`, `from_piece`, `from_player`, `from_status`, `piece_idx`, `player_code`, `result_str`, `to_format`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FourGame>>
abstract class FourGame implements RustOpaqueInterface {
  /// The greedy bot's move (UCI form) for the side to move, or None if none.
  String? botMove({required BigInt seed});

  /// Destination squares (row*14+col) of every legal move from `from`.
  Uint32List legalTargets({required int from});

  static FourGame newGame({required FourFormat format}) =>
      RustLib.instance.api.crateApiFourFourGameNewGame(format: format);

  MoveOutcome play({
    required int from,
    required int to,
    FourPieceKind? promotion,
  });

  /// Apply a move in coordinate form ("d1d2", "d2d3q"); for bot/remote moves.
  bool playUci({required String uci});

  /// Geometric premove destinations for the piece on `from`, ignoring whose
  /// turn it is (for premove highlighting). Re-validated when it executes.
  Uint32List premoveTargets({required int from});

  /// Premove targets for `from` after the queued premoves (flattened
  /// [f0,t0,f1,t1,…]) are applied as raw relocations — for premove chains.
  Uint32List premoveTargetsAfter({
    required List<int> premoves,
    required int from,
  });

  FourView view();
}

enum FourFormat { teams, freeForAll }

enum FourPieceKind { pawn, knight, bishop, rook, queen, king }

enum FourPlayer { red, blue, yellow, green }

class FourPlayerPanel {
  final FourPlayer player;
  final FourPlayerStatus status;
  final int score;
  final bool inCheck;

  const FourPlayerPanel({
    required this.player,
    required this.status,
    required this.score,
    required this.inCheck,
  });

  @override
  int get hashCode =>
      player.hashCode ^ status.hashCode ^ score.hashCode ^ inCheck.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FourPlayerPanel &&
          runtimeType == other.runtimeType &&
          player == other.player &&
          status == other.status &&
          score == other.score &&
          inCheck == other.inCheck;
}

enum FourPlayerStatus { active, checkmated, stalemated, resigned }

class FourSquarePiece {
  final FourPlayer player;
  final FourPieceKind kind;

  const FourSquarePiece({required this.player, required this.kind});

  @override
  int get hashCode => player.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FourSquarePiece &&
          runtimeType == other.runtimeType &&
          player == other.player &&
          kind == other.kind;
}

class FourView {
  /// 196 cells, index = row*14 + col. Cut corners + empty squares are None.
  final List<FourSquarePiece?> board;

  /// 196 validity flags (false = cut corner → painted as a hole).
  final List<bool> valid;
  final FourPlayer turn;
  final List<FourPlayerPanel> players;
  final int? lastFrom;
  final int? lastTo;
  final FourFormat format;

  /// "ongoing" | "team:red_yellow" | "team:blue_green" | "ffa:red" | ...
  final String result;

  const FourView({
    required this.board,
    required this.valid,
    required this.turn,
    required this.players,
    this.lastFrom,
    this.lastTo,
    required this.format,
    required this.result,
  });

  @override
  int get hashCode =>
      board.hashCode ^
      valid.hashCode ^
      turn.hashCode ^
      players.hashCode ^
      lastFrom.hashCode ^
      lastTo.hashCode ^
      format.hashCode ^
      result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FourView &&
          runtimeType == other.runtimeType &&
          board == other.board &&
          valid == other.valid &&
          turn == other.turn &&
          players == other.players &&
          lastFrom == other.lastFrom &&
          lastTo == other.lastTo &&
          format == other.format &&
          result == other.result;
}
