// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply`, `captured`, `from_color`, `from_kind`, `from_variant`, `insufficient_to_mate`, `is_over`, `passable_capture`, `pawn_premove`, `premove_targets_on`, `relocate`, `to_color`, `to_kind`, `to_outcome`, `to_variant`, `with_clock`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChessGame>>
abstract class ChessGame implements RustOpaqueInterface {
  /// Cheap clock-only snapshot (no board build).
  ClockSnapshot clockSnapshot();

  /// Crazyhouse: legal squares to drop the reserve piece `piece` (0=Pawn ..
  /// 4=Queen) onto.
  Uint32List dropTargets({required int piece});

  static ChessGame fromFen({required String fen}) =>
      RustLib.instance.api.crateApiGameChessGameFromFen(fen: fen);

  /// Bughouse: receive a piece passed from the partner's board into `color`'s
  /// reserve. Refreshes status (a fed piece can create a drop-mate escape).
  void giveToHand({required PieceColor color, required PieceKind piece});

  /// Position-hash history (for the AI's repetition avoidance).
  Uint64List hashHistory();

  /// Bughouse: the piece the last applied move made available to pass to the
  /// partner (already demoted to a pawn if it was a promoted piece).
  PieceKind? lastPassableCapture();

  /// Destination squares of every legal move starting from `from` (for hints).
  Uint32List legalTargets({required int from});

  /// The moves played so far in UCI form (for saving a game).
  List<String> moveHistoryUci();

  /// New game with no clock.
  static ChessGame newGame() =>
      RustLib.instance.api.crateApiGameChessGameNewGame();

  /// New game with a Fischer time control (`base_minutes` + `increment_seconds`).
  static ChessGame newTimed({
    required int baseMinutes,
    required int incrementSeconds,
  }) => RustLib.instance.api.crateApiGameChessGameNewTimed(
    baseMinutes: baseMinutes,
    incrementSeconds: incrementSeconds,
  );

  /// New game of `variant`. Standard start position, except Chess960 which is
  /// built from `chess960_index` (mod 960). `base_minutes`/`increment_seconds`
  /// of 0/0 means no clock.
  static ChessGame newVariant({
    required GameVariant variant,
    required int baseMinutes,
    required int incrementSeconds,
    required int chess960Index,
  }) => RustLib.instance.api.crateApiGameChessGameNewVariant(
    variant: variant,
    baseMinutes: baseMinutes,
    incrementSeconds: incrementSeconds,
    chess960Index: chess960Index,
  );

  /// Try to play from→to (with optional promotion piece).
  MoveOutcome play({required int from, required int to, PieceKind? promotion});

  /// Crazyhouse: drop reserve `piece` (0=Pawn .. 4=Queen) onto square `to`.
  MoveOutcome playDrop({required int piece, required int to});

  /// Apply a move given in UCI/coordinate form (e.g. `e2e4`, `e7e8q`), used
  /// to apply the AI's chosen move. Returns false if illegal/over.
  bool playUci({required String uci});

  /// Geometric destination squares for the piece on `from`, ignoring whose
  /// turn it is (for premove candidate highlighting). Approximate: validity is
  /// re-checked when the premove is actually executed.
  Uint32List premoveTargets({required int from});

  /// Premove targets for `from` AFTER the queued premoves are applied as raw
  /// relocations (flattened from,to pairs: [f0,t0,f1,t1,…]). Lets a premove
  /// *chain* target the board the earlier premoves would produce. Each
  /// premove's real legality is still re-checked when it executes.
  Uint32List premoveTargetsAfter({
    required List<int> premoves,
    required int from,
  });

  /// Reconcile the clock from a LAN peer's move message.
  void setClockMs({
    required PlatformInt64 whiteMs,
    required PlatformInt64 blackMs,
  });

  /// Advance the running side's clock by `elapsed_ms`. Latches a timeout when
  /// the side to move flags.
  void tick({required int elapsedMs});

  /// Take back the last move (and restore the clock).
  bool undo();

  GameView view();

  /// Fog of War: the squares `viewer` can see (own pieces + observed squares).
  Uint32List visibleSquares({required PieceColor viewer});
}

/// Lightweight clock-only snapshot, polled at high frequency by the clock UI so
/// the board does not rebuild on every tick.
class ClockSnapshot {
  final bool infinite;
  final PlatformInt64 whiteMs;
  final PlatformInt64 blackMs;
  final PieceColor running;
  final bool over;

  const ClockSnapshot({
    required this.infinite,
    required this.whiteMs,
    required this.blackMs,
    required this.running,
    required this.over,
  });

  @override
  int get hashCode =>
      infinite.hashCode ^
      whiteMs.hashCode ^
      blackMs.hashCode ^
      running.hashCode ^
      over.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClockSnapshot &&
          runtimeType == other.runtimeType &&
          infinite == other.infinite &&
          whiteMs == other.whiteMs &&
          blackMs == other.blackMs &&
          running == other.running &&
          over == other.over;
}

/// Flattened (payload-free, so no `freezed` dependency is needed on Dart).
enum GameOutcome {
  ongoing,
  whiteWins,
  blackWins,
  whiteWinsOnTime,
  blackWinsOnTime,
  stalemate,
  drawFiftyMove,
  drawThreefold,
  drawInsufficientMaterial,
}

/// Game variant exposed to Flutter.
enum GameVariant {
  standard,
  threeCheck,
  kingOfTheHill,
  chess960,
  atomic,
  crazyhouse,
  bughouse,
  fogOfWar,
}

/// A complete snapshot for rendering. Board index 0 = a1, 63 = h8.
class GameView {
  final List<SquarePiece?> board;
  final PieceColor sideToMove;
  final bool inCheck;
  final GameOutcome status;
  final int? lastFrom;
  final int? lastTo;
  final List<String> sanMoves;
  final List<PieceKind> capturedByWhite;
  final List<PieceKind> capturedByBlack;
  final int halfmove;
  final int fullmove;
  final String fen;

  /// Active variant + Three-check counters (0 for other variants).
  final GameVariant variant;
  final int whiteChecks;
  final int blackChecks;

  /// The last move was an Atomic explosion (drive the blast animation).
  final bool lastExplosion;

  /// Crazyhouse reserve counts [Pawn,Knight,Bishop,Rook,Queen] per colour, and
  /// the promoted-square mask (for the AI). Empty/0 for other variants.
  final Uint32List whiteHand;
  final Uint32List blackHand;
  final BigInt promoted;
  final bool clockInfinite;
  final PlatformInt64 clockWhiteMs;
  final PlatformInt64 clockBlackMs;
  final PieceColor clockRunning;

  const GameView({
    required this.board,
    required this.sideToMove,
    required this.inCheck,
    required this.status,
    this.lastFrom,
    this.lastTo,
    required this.sanMoves,
    required this.capturedByWhite,
    required this.capturedByBlack,
    required this.halfmove,
    required this.fullmove,
    required this.fen,
    required this.variant,
    required this.whiteChecks,
    required this.blackChecks,
    required this.lastExplosion,
    required this.whiteHand,
    required this.blackHand,
    required this.promoted,
    required this.clockInfinite,
    required this.clockWhiteMs,
    required this.clockBlackMs,
    required this.clockRunning,
  });

  @override
  int get hashCode =>
      board.hashCode ^
      sideToMove.hashCode ^
      inCheck.hashCode ^
      status.hashCode ^
      lastFrom.hashCode ^
      lastTo.hashCode ^
      sanMoves.hashCode ^
      capturedByWhite.hashCode ^
      capturedByBlack.hashCode ^
      halfmove.hashCode ^
      fullmove.hashCode ^
      fen.hashCode ^
      variant.hashCode ^
      whiteChecks.hashCode ^
      blackChecks.hashCode ^
      lastExplosion.hashCode ^
      whiteHand.hashCode ^
      blackHand.hashCode ^
      promoted.hashCode ^
      clockInfinite.hashCode ^
      clockWhiteMs.hashCode ^
      clockBlackMs.hashCode ^
      clockRunning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameView &&
          runtimeType == other.runtimeType &&
          board == other.board &&
          sideToMove == other.sideToMove &&
          inCheck == other.inCheck &&
          status == other.status &&
          lastFrom == other.lastFrom &&
          lastTo == other.lastTo &&
          sanMoves == other.sanMoves &&
          capturedByWhite == other.capturedByWhite &&
          capturedByBlack == other.capturedByBlack &&
          halfmove == other.halfmove &&
          fullmove == other.fullmove &&
          fen == other.fen &&
          variant == other.variant &&
          whiteChecks == other.whiteChecks &&
          blackChecks == other.blackChecks &&
          lastExplosion == other.lastExplosion &&
          whiteHand == other.whiteHand &&
          blackHand == other.blackHand &&
          promoted == other.promoted &&
          clockInfinite == other.clockInfinite &&
          clockWhiteMs == other.clockWhiteMs &&
          clockBlackMs == other.clockBlackMs &&
          clockRunning == other.clockRunning;
}

/// Result of attempting a move from one square to another.
enum MoveOutcome {
  played,

  /// from→to is a legal pawn move to the last rank; the UI must pick a piece
  /// and call `play` again with `promotion` set.
  needsPromotion,
  illegal,
}

enum PieceColor { white, black }

enum PieceKind { pawn, knight, bishop, rook, queen, king }

class SquarePiece {
  final PieceColor color;
  final PieceKind kind;

  const SquarePiece({required this.color, required this.kind});

  @override
  int get hashCode => color.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SquarePiece &&
          runtimeType == other.runtimeType &&
          color == other.color &&
          kind == other.kind;
}
