// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bug_assign_notify`, `bug_authority`, `bug_broadcast`, `bug_check_end`, `bug_client_handle`, `bug_client_out`, `bug_cmd`, `bug_finish`, `bug_game`, `bug_host_task`, `bug_inbound`, `bug_join_task`, `bug_passable`, `bug_reader`, `bug_team`, `bug_writer`, `cmd_slot`, `color_u8`, `drive`, `es`, `feed_target`, `four_apply_uci`, `four_assign_notify`, `four_authority`, `four_client_handle`, `four_client_out`, `four_cmd`, `four_finish`, `four_format`, `four_host_task`, `four_inbound`, `four_join_task`, `four_player_code`, `four_result_str`, `handle_incoming`, `host_task`, `join_task`, `lock`, `of`, `piece_u8`, `read_message`, `runtime`, `seat_board`, `seat_index`, `send`, `session_cancel`, `variant_from_code`, `variant_game`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// Browse for LAN hosts. Streams each resolved host until `net_stop_browse`.
Stream<NetHost> netBrowse() => RustLib.instance.api.crateApiNetNetBrowse();

void netStopBrowse() => RustLib.instance.api.crateApiNetNetStopBrowse();

/// Host a game: advertise on mDNS, accept one peer, then run the session.
Stream<NetEvent> netHost({
  required String name,
  required int baseMinutes,
  required int incrementSeconds,
  required bool hostWhite,
  required String variant,
  required int chess960Index,
}) => RustLib.instance.api.crateApiNetNetHost(
  name: name,
  baseMinutes: baseMinutes,
  incrementSeconds: incrementSeconds,
  hostWhite: hostWhite,
  variant: variant,
  chess960Index: chess960Index,
);

/// Join a host at `addr` ("ip:port").
Stream<NetEvent> netJoin({required String addr, required String name}) =>
    RustLib.instance.api.crateApiNetNetJoin(addr: addr, name: name);

void netSendMove({
  required String uci,
  required PlatformInt64 whiteMs,
  required PlatformInt64 blackMs,
}) => RustLib.instance.api.crateApiNetNetSendMove(
  uci: uci,
  whiteMs: whiteMs,
  blackMs: blackMs,
);

void netResign() => RustLib.instance.api.crateApiNetNetResign();

void netOfferDraw() => RustLib.instance.api.crateApiNetNetOfferDraw();

void netRespondDraw({required bool accept}) =>
    RustLib.instance.api.crateApiNetNetRespondDraw(accept: accept);

void netSendChat({required String text}) =>
    RustLib.instance.api.crateApiNetNetSendChat(text: text);

void netLeave() => RustLib.instance.api.crateApiNetNetLeave();

/// Host a Bughouse match: advertise (name prefixed "[BH]"), accept up to 3
/// joiners into a lobby, then — once the host assigns seats — run the authority.
Stream<NetEvent> netHostBughouse({
  required String name,
  required int baseMinutes,
  required int incrementSeconds,
}) => RustLib.instance.api.crateApiNetNetHostBughouse(
  name: name,
  baseMinutes: baseMinutes,
  incrementSeconds: incrementSeconds,
);

/// Join a Bughouse host at `addr`; mirror its broadcasts as NetEvents.
Stream<NetEvent> netJoinBughouse({
  required String addr,
  required String name,
}) => RustLib.instance.api.crateApiNetNetJoinBughouse(addr: addr, name: name);

/// Host assigns the four seats and starts the match. `seat_owner[seat]` is the
/// connection index (join order, 0-based) or -1 for the host.
void netBugStart({required List<int> seatOwner}) =>
    RustLib.instance.api.crateApiNetNetBugStart(seatOwner: seatOwner);

void netSendBugMove({
  required int board,
  required String uci,
  required PlatformInt64 whiteMs,
  required PlatformInt64 blackMs,
}) => RustLib.instance.api.crateApiNetNetSendBugMove(
  board: board,
  uci: uci,
  whiteMs: whiteMs,
  blackMs: blackMs,
);

void netBugResign({required int seat}) =>
    RustLib.instance.api.crateApiNetNetBugResign(seat: seat);

/// Host a 4-player match: advertise "[4P]", accept ≤3 joiners, run the authority.
Stream<NetEvent> netHostFour({required String name, required String format}) =>
    RustLib.instance.api.crateApiNetNetHostFour(name: name, format: format);

Stream<NetEvent> netJoinFour({required String addr, required String name}) =>
    RustLib.instance.api.crateApiNetNetJoinFour(addr: addr, name: name);

void netFourStart({required List<int> seatOwner}) =>
    RustLib.instance.api.crateApiNetNetFourStart(seatOwner: seatOwner);

void netSendFourMove({required int seat, required String uci}) =>
    RustLib.instance.api.crateApiNetNetSendFourMove(seat: seat, uci: uci);

void netFourResign({required int seat}) =>
    RustLib.instance.api.crateApiNetNetFourResign(seat: seat);

/// A flattened event (no payload enum, so no `freezed` needed on Dart).
class NetEvent {
  final NetEventKind kind;
  final bool youAreWhite;
  final String whiteName;
  final String blackName;
  final int baseMinutes;
  final int incrementSeconds;
  final String fen;
  final String uci;
  final PlatformInt64 whiteMs;
  final PlatformInt64 blackMs;
  final bool drawAccepted;
  final String text;

  /// Variant code agreed for this game (e.g. "standard", "crazyhouse").
  final String variant;
  final int board;
  final int toBoard;
  final int toColor;
  final int piece;
  final int seat;
  final int winningTeam;
  final Uint32List yourSeats;
  final List<String> seats;

  const NetEvent({
    required this.kind,
    required this.youAreWhite,
    required this.whiteName,
    required this.blackName,
    required this.baseMinutes,
    required this.incrementSeconds,
    required this.fen,
    required this.uci,
    required this.whiteMs,
    required this.blackMs,
    required this.drawAccepted,
    required this.text,
    required this.variant,
    required this.board,
    required this.toBoard,
    required this.toColor,
    required this.piece,
    required this.seat,
    required this.winningTeam,
    required this.yourSeats,
    required this.seats,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      youAreWhite.hashCode ^
      whiteName.hashCode ^
      blackName.hashCode ^
      baseMinutes.hashCode ^
      incrementSeconds.hashCode ^
      fen.hashCode ^
      uci.hashCode ^
      whiteMs.hashCode ^
      blackMs.hashCode ^
      drawAccepted.hashCode ^
      text.hashCode ^
      variant.hashCode ^
      board.hashCode ^
      toBoard.hashCode ^
      toColor.hashCode ^
      piece.hashCode ^
      seat.hashCode ^
      winningTeam.hashCode ^
      yourSeats.hashCode ^
      seats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          youAreWhite == other.youAreWhite &&
          whiteName == other.whiteName &&
          blackName == other.blackName &&
          baseMinutes == other.baseMinutes &&
          incrementSeconds == other.incrementSeconds &&
          fen == other.fen &&
          uci == other.uci &&
          whiteMs == other.whiteMs &&
          blackMs == other.blackMs &&
          drawAccepted == other.drawAccepted &&
          text == other.text &&
          variant == other.variant &&
          board == other.board &&
          toBoard == other.toBoard &&
          toColor == other.toColor &&
          piece == other.piece &&
          seat == other.seat &&
          winningTeam == other.winningTeam &&
          yourSeats == other.yourSeats &&
          seats == other.seats;
}

enum NetEventKind {
  connected,
  move,
  resign,
  drawOffer,
  drawResponse,
  chat,
  disconnected,
  error,
  bugJoin,
  bugStart,
  bugMove,
  bugPass,
  bugResult,
  fourJoin,
  fourStart,
  fourMove,
  fourResult,
}

/// A host discovered on the LAN.
class NetHost {
  final String name;
  final String addr;
  final String timeControl;

  const NetHost({
    required this.name,
    required this.addr,
    required this.timeControl,
  });

  @override
  int get hashCode => name.hashCode ^ addr.hashCode ^ timeControl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetHost &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          addr == other.addr &&
          timeControl == other.timeControl;
}
